#logging:
#  level:
#    root: DEBUG

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

#  cloud:
#    consul:
#      discovery:
#        health-check-interval: 1m

#springdoc:
#  swagger-ui:
#    path: /api-docs
#
#server:
#  forward-headers-strategy: framework